-- MySQL Script generated by MySQL Workbench
-- Mon Apr 16 03:48:48 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Contact`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Contact` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Contact` (
  `Contact_ID` INT NOT NULL,
  `Contact_FirstName` VARCHAR(45) NULL,
  `Contact_LastName` VARCHAR(45) NULL,
  `Contact_Address` VARCHAR(45) NULL,
  `Contact_Email` VARCHAR(45) NULL,
  `Contact_PhoneNumber` VARCHAR(45) NULL,
  PRIMARY KEY (`Contact_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Employee` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Employee` (
  `Employee_ID` INT NOT NULL,
  `Contact_ID` INT NOT NULL,
  `Employee_Type` VARCHAR(45) NULL,
  PRIMARY KEY (`Employee_ID`),
  INDEX `Contact_ID_idx` (`Contact_ID` ASC),
  CONSTRAINT `Contact_ID`
    FOREIGN KEY (`Contact_ID`)
    REFERENCES `mydb`.`Contact` (`Contact_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Service`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Service` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Service` (
  `Service_ID` INT NOT NULL,
  `Service_Name` VARCHAR(45) NULL,
  `Service_Price` DECIMAL(10,2) NULL,
  `Service_Duration_minutes` INT NULL,
  `Service_Type` VARCHAR(45) NULL,
  PRIMARY KEY (`Service_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Massage Service`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Massage Service` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Massage Service` (
  `Service_ID` INT NOT NULL,
  `Massage_Speciality` VARCHAR(45) NULL,
  `Massage_Description` VARCHAR(150) NULL,
  PRIMARY KEY (`Service_ID`),
  CONSTRAINT `Serv_ID`
    FOREIGN KEY (`Service_ID`)
    REFERENCES `mydb`.`Service` (`Service_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Private Company`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Private Company` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Private Company` (
  `Company_ID` INT NOT NULL,
  `Company_Name` VARCHAR(45) NULL,
  `Company_PhoneNumber` VARCHAR(40) NULL,
  `Company_CommisionRate` DECIMAL(10,2) NULL,
  `Company_CommunityRating` INT NULL COMMENT 'Out of 100, Rounded to Nearest Integer.',
  PRIMARY KEY (`Company_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Entrepreneur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Entrepreneur` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Entrepreneur` (
  `Employee_ID` INT NOT NULL,
  `Company_ID` INT NOT NULL,
  `Entrepreneur_JoinDate` DATE NULL,
  `Entrepreneur_Type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Employee_ID`),
  UNIQUE INDEX `Company_ID_idx` (`Company_ID` ASC),
  CONSTRAINT `Employee_ID`
    FOREIGN KEY (`Employee_ID`)
    REFERENCES `mydb`.`Employee` (`Employee_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Company_ID`
    FOREIGN KEY (`Company_ID`)
    REFERENCES `mydb`.`Private Company` (`Company_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Staff`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Staff` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Staff` (
  `Employee_ID` INT NOT NULL,
  `Staff_HireDate` DATE NULL,
  `Staff_Position` VARCHAR(45) NULL,
  `Staff_Salary_per_month` INT NULL,
  PRIMARY KEY (`Employee_ID`),
  CONSTRAINT `Employe_ID`
    FOREIGN KEY (`Employee_ID`)
    REFERENCES `mydb`.`Employee` (`Employee_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Client` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Client` (
  `Client_ID` INT NOT NULL,
  `Contact_ID` INT NOT NULL,
  `Client_Type` VARCHAR(45) NULL,
  PRIMARY KEY (`Client_ID`),
  INDEX `Contact_ID_idx` (`Contact_ID` ASC),
  CONSTRAINT `Contac_ID`
    FOREIGN KEY (`Contact_ID`)
    REFERENCES `mydb`.`Contact` (`Contact_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Appointment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Appointment` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Appointment` (
  `Client_ID` INT NOT NULL,
  `Employee_ID` INT NOT NULL,
  `Service_ID` INT NOT NULL,
  `Appointment_ID` INT NOT NULL,
  `Appointment_Date` DATE NULL,
  `Appointment_Time` TIME NULL,
  `Appointment_RoomNumber` VARCHAR(45) NULL,
  PRIMARY KEY (`Client_ID`, `Employee_ID`, `Service_ID`, `Appointment_ID`),
  INDEX `Employee_ID_idx` (`Employee_ID` ASC),
  INDEX `Service_ID_idx` (`Service_ID` ASC),
  CONSTRAINT `Clie_ID`
    FOREIGN KEY (`Client_ID`)
    REFERENCES `mydb`.`Client` (`Client_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Emplo_ID`
    FOREIGN KEY (`Employee_ID`)
    REFERENCES `mydb`.`Entrepreneur` (`Employee_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Servic_ID`
    FOREIGN KEY (`Service_ID`)
    REFERENCES `mydb`.`Service` (`Service_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Equipment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Equipment` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Equipment` (
  `Equipment_ID` INT NOT NULL,
  `Equipment_Name` VARCHAR(45) NULL,
  `Equipment_PurchaseDate` DATE NULL,
  `Equipment_Size` VARCHAR(45) NULL,
  `Equipment_Description` VARCHAR(45) NULL,
  `Equipment_Cost` DECIMAL(10,2) NULL,
  `Equipment_Type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Equipment_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Massage Equipment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Massage Equipment` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Massage Equipment` (
  `Equipment_ID` INT NOT NULL,
  `Massage_TimesUsed` INT NULL DEFAULT 0,
  PRIMARY KEY (`Equipment_ID`),
  CONSTRAINT `Equipment_ID`
    FOREIGN KEY (`Equipment_ID`)
    REFERENCES `mydb`.`Equipment` (`Equipment_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Dentistry Equipment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Dentistry Equipment` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Dentistry Equipment` (
  `Equipment_ID` INT NOT NULL,
  `Dentistry_MedicalProductNumber` VARCHAR(40) NULL,
  PRIMARY KEY (`Equipment_ID`),
  CONSTRAINT `Equ_ID`
    FOREIGN KEY (`Equipment_ID`)
    REFERENCES `mydb`.`Equipment` (`Equipment_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Certification`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Certification` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Certification` (
  `Certification_ID` INT NOT NULL,
  `Certification_Type` VARCHAR(100) NULL,
  `Certfication_Issuer` VARCHAR(150) NULL,
  PRIMARY KEY (`Certification_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Subscription`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Subscription` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Subscription` (
  `Subscription_ID` INT NOT NULL,
  `Subscription_StartDate` DATE NULL,
  `Subscription_MonthlyFee` DECIMAL(10,2) NULL,
  `Subscription_ReducedRate` DECIMAL(10,2) NULL,
  `Client_ID` INT NOT NULL,
  PRIMARY KEY (`Subscription_ID`, `Client_ID`),
  INDEX `Client_ID_idx` (`Client_ID` ASC),
  CONSTRAINT `Client_ID`
    FOREIGN KEY (`Client_ID`)
    REFERENCES `mydb`.`Client` (`Client_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Dentistry Service`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Dentistry Service` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Dentistry Service` (
  `Service_ID` INT NOT NULL,
  `Dentistry_Description` VARCHAR(45) NULL,
  `Dentistry_Recommendation` VARCHAR(250) NULL,
  PRIMARY KEY (`Service_ID`),
  CONSTRAINT `S_ID`
    FOREIGN KEY (`Service_ID`)
    REFERENCES `mydb`.`Service` (`Service_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Physiotherapy Service`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Physiotherapy Service` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Physiotherapy Service` (
  `Service_ID` INT NOT NULL,
  `Physiotherapy_ExerciseName` VARCHAR(30) NULL,
  `Physiotherapy_Description` VARCHAR(350) NULL,
  PRIMARY KEY (`Service_ID`),
  CONSTRAINT `Servicee_ID`
    FOREIGN KEY (`Service_ID`)
    REFERENCES `mydb`.`Service` (`Service_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Storage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Storage` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Storage` (
  `Employee_ID` INT NOT NULL,
  `Equipment_ID` INT NOT NULL,
  PRIMARY KEY (`Employee_ID`, `Equipment_ID`),
  INDEX `Equipment_ID_idx` (`Equipment_ID` ASC),
  CONSTRAINT `Empyye_ID`
    FOREIGN KEY (`Employee_ID`)
    REFERENCES `mydb`.`Entrepreneur` (`Employee_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Equint_ID`
    FOREIGN KEY (`Equipment_ID`)
    REFERENCES `mydb`.`Equipment` (`Equipment_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Massage Therapist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Massage Therapist` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Massage Therapist` (
  `Employee_ID` INT NOT NULL,
  `Certification_ID` INT NOT NULL,
  `MessageTherapist_CertifiedMTNumber` INT NULL COMMENT 'certified massage therapist number',
  PRIMARY KEY (`Employee_ID`),
  INDEX `Certification_ID_idx` (`Certification_ID` ASC),
  CONSTRAINT `Eyee_ID`
    FOREIGN KEY (`Employee_ID`)
    REFERENCES `mydb`.`Entrepreneur` (`Employee_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Certification_ID`
    FOREIGN KEY (`Certification_ID`)
    REFERENCES `mydb`.`Certification` (`Certification_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Dentist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Dentist` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Dentist` (
  `Employee_ID` INT NOT NULL,
  `Certification_ID` INT NOT NULL,
  `Dentist_BCDNumber` INT NULL COMMENT 'Board of Certified Dentists Number',
  `Dentist_UniversityDegree` VARCHAR(45) NULL,
  `Dentist_DegreeDate` DATE NULL,
  PRIMARY KEY (`Employee_ID`),
  INDEX `Certification_ID_idx` (`Certification_ID` ASC),
  CONSTRAINT `Eee_ID`
    FOREIGN KEY (`Employee_ID`)
    REFERENCES `mydb`.`Entrepreneur` (`Employee_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Cerification_ID`
    FOREIGN KEY (`Certification_ID`)
    REFERENCES `mydb`.`Certification` (`Certification_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Physiotherapist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Physiotherapist` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Physiotherapist` (
  `Employee_ID` INT NOT NULL,
  `Certification_ID` INT NOT NULL,
  `Physiotherapist_CPNumber` INT NULL COMMENT 'certified physiotherapist number',
  PRIMARY KEY (`Employee_ID`),
  INDEX `Certification_ID_idx` (`Certification_ID` ASC),
  CONSTRAINT `Empe_ID`
    FOREIGN KEY (`Employee_ID`)
    REFERENCES `mydb`.`Entrepreneur` (`Employee_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Certificn_ID`
    FOREIGN KEY (`Certification_ID`)
    REFERENCES `mydb`.`Certification` (`Certification_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
